# Generated by Django 6.1 on 2026-08-28 02:12

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='BacktestSettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('initial_equity', models.FloatField(default=10000.0)),
                ('fee', models.FloatField(default=0.0)),
                ('commission_per_lot', models.FloatField(default=7.0)),
                ('spread', models.FloatField(default=0.25)),
                ('slippage', models.FloatField(default=0.0001)),
                ('risk_pct', models.FloatField(default=0.01)),
                ('contract_size', models.FloatField(default=100.0)),
                ('in_sample_end', models.DateField(blank=True, null=True)),
                ('oos_start', models.DateField(blank=True, null=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Backtest defaults',
                'verbose_name_plural': 'Backtest defaults',
            },
        ),
    ]
