# Generated by Django 6.1 on 2026-08-28 02:44

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='StrategyDefinition',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('slug', models.SlugField(max_length=128, unique=True)),
                ('label', models.CharField(max_length=128)),
                ('description', models.TextField(blank=True)),
                ('schema_version', models.PositiveSmallIntegerField(default=1)),
                ('definition_json', models.JSONField(default=dict)),
                ('allow_short', models.BooleanField(default=False)),
                ('is_builtin', models.BooleanField(default=False)),
                ('status', models.CharField(choices=[('draft', 'draft'), ('active', 'active'), ('archived', 'archived')], db_index=True, default='draft', max_length=16)),
                ('logic_spec', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='strategy_definitions', to=settings.AUTH_USER_MODEL)),
                ('parent', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='forks', to='strategies.strategydefinition')),
            ],
            options={
                'ordering': ['-updated_at'],
            },
        ),
    ]
