# Generated by Django 6.1 on 2026-08-28 01:50

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('backtests', '0003_decisiongate_montecarlosummary_robustnessrow'),
    ]

    operations = [
        migrations.CreateModel(
            name='ExportFile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('kind', models.CharField(choices=[('md', 'md'), ('txt', 'txt')], max_length=8)),
                ('path', models.CharField(max_length=512)),
                ('filename', models.CharField(max_length=256)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('run', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='exports', to='backtests.backtestrun')),
            ],
            options={
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['run'], name='reports_exp_run_id_8ec879_idx')],
            },
        ),
    ]
