# Generated by Django 6.1 on 2026-08-28 00:07

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('marketdata', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='BacktestRun',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('strategy_name', models.CharField(max_length=128)),
                ('params', models.JSONField(blank=True, default=dict)),
                ('initial_equity', models.FloatField(default=10000.0)),
                ('fee', models.FloatField(default=0.0)),
                ('commission_per_lot', models.FloatField(default=7.0)),
                ('spread', models.FloatField(default=0.25)),
                ('slippage', models.FloatField(default=0.0001)),
                ('risk_pct', models.FloatField(default=0.01)),
                ('contract_size', models.FloatField(default=100.0)),
                ('in_sample_end', models.DateField(blank=True, null=True)),
                ('oos_start', models.DateField(blank=True, null=True)),
                ('multi_deep', models.BooleanField(default=False)),
                ('status', models.CharField(choices=[('queued', 'queued'), ('running', 'running'), ('done', 'done'), ('failed', 'failed')], db_index=True, default='queued', max_length=16)),
                ('error_message', models.TextField(blank=True)),
                ('task_id', models.CharField(blank=True, max_length=64)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('started_at', models.DateTimeField(blank=True, null=True)),
                ('finished_at', models.DateTimeField(blank=True, null=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='backtest_runs', to=settings.AUTH_USER_MODEL)),
                ('dataset', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='runs', to='marketdata.dataset')),
                ('parent', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='children', to='backtests.backtestrun')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='MetricSet',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('split', models.CharField(default='full', max_length=32)),
                ('label', models.CharField(blank=True, max_length=64)),
                ('final_equity', models.FloatField(blank=True, null=True)),
                ('total_return', models.FloatField(blank=True, null=True)),
                ('cagr', models.FloatField(blank=True, null=True)),
                ('sharpe', models.FloatField(blank=True, null=True)),
                ('sortino', models.FloatField(blank=True, null=True)),
                ('calmar', models.FloatField(blank=True, null=True)),
                ('max_drawdown', models.FloatField(blank=True, null=True)),
                ('win_rate', models.FloatField(blank=True, null=True)),
                ('profit_factor', models.FloatField(blank=True, null=True)),
                ('expectancy', models.FloatField(blank=True, null=True)),
                ('average_win', models.FloatField(blank=True, null=True)),
                ('average_loss', models.FloatField(blank=True, null=True)),
                ('trades', models.IntegerField(blank=True, null=True)),
                ('average_trade', models.FloatField(blank=True, null=True)),
                ('longest_losing_streak', models.IntegerField(blank=True, null=True)),
                ('recovery_factor', models.FloatField(blank=True, null=True)),
                ('years', models.FloatField(blank=True, null=True)),
                ('extras', models.JSONField(blank=True, default=dict)),
                ('run', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='metrics', to='backtests.backtestrun')),
            ],
            options={
                'indexes': [models.Index(fields=['run', 'split'], name='backtests_m_run_id_95fb62_idx')],
            },
        ),
        migrations.CreateModel(
            name='Trade',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('entry_time', models.DateTimeField()),
                ('exit_time', models.DateTimeField()),
                ('direction', models.SmallIntegerField()),
                ('entry', models.FloatField()),
                ('exit', models.FloatField()),
                ('lots', models.FloatField()),
                ('pnl', models.FloatField()),
                ('return_pct', models.FloatField()),
                ('reason', models.CharField(max_length=16)),
                ('run', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='trades', to='backtests.backtestrun')),
            ],
            options={
                'indexes': [models.Index(fields=['run'], name='backtests_t_run_id_a663d5_idx')],
            },
        ),
    ]
