# Generated by Django 6.1 on 2026-08-28 01:46

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backtests', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='WalkForwardFold',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dev_start', models.DateField()),
                ('dev_end', models.DateField()),
                ('val_start', models.DateField()),
                ('val_end', models.DateField()),
                ('best_ema_fast', models.IntegerField(blank=True, null=True)),
                ('dev_sharpe', models.FloatField(blank=True, null=True)),
                ('val_sharpe', models.FloatField(blank=True, null=True)),
                ('val_return', models.FloatField(blank=True, null=True)),
                ('val_max_dd', models.FloatField(blank=True, null=True)),
                ('val_trades', models.IntegerField(blank=True, null=True)),
                ('positive_sharpe', models.BooleanField(default=False)),
                ('run', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='wf_folds', to='backtests.backtestrun')),
            ],
            options={
                'ordering': ['dev_start'],
                'indexes': [models.Index(fields=['run'], name='backtests_w_run_id_5c0feb_idx')],
            },
        ),
    ]
