# Generated by Django 6.1 on 2026-08-28 01:50

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backtests', '0002_walkforwardfold'),
    ]

    operations = [
        migrations.CreateModel(
            name='DecisionGate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('in_sample', models.BooleanField(default=False)),
                ('out_of_sample', models.BooleanField(default=False)),
                ('walk_forward', models.BooleanField(default=False)),
                ('parameter_stability', models.BooleanField(default=False)),
                ('cost_stress', models.BooleanField(default=False)),
                ('monte_carlo', models.BooleanField(default=False)),
                ('status', models.CharField(choices=[('FAIL', 'FAIL'), ('FRAGILE', 'FRAGILE'), ('ACCEPTABLE', 'ACCEPTABLE'), ('ROBUST', 'ROBUST')], default='FAIL', max_length=16)),
                ('implement_mql5', models.BooleanField(default=False)),
                ('n_pass', models.IntegerField(default=0)),
                ('run', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='decision_gate', to='backtests.backtestrun')),
            ],
        ),
        migrations.CreateModel(
            name='MonteCarloSummary',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('mode', models.CharField(max_length=32)),
                ('n_sims', models.IntegerField(default=10000)),
                ('median_final', models.FloatField(blank=True, null=True)),
                ('p5_final', models.FloatField(blank=True, null=True)),
                ('p25_final', models.FloatField(blank=True, null=True)),
                ('p50_final', models.FloatField(blank=True, null=True)),
                ('p75_final', models.FloatField(blank=True, null=True)),
                ('p95_final', models.FloatField(blank=True, null=True)),
                ('median_max_dd', models.FloatField(blank=True, null=True)),
                ('p95_worst_dd', models.FloatField(blank=True, null=True)),
                ('prob_loss', models.FloatField(blank=True, null=True)),
                ('prob_dd_gt_30', models.FloatField(blank=True, null=True)),
                ('extras', models.JSONField(blank=True, default=dict)),
                ('run', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='mc_summaries', to='backtests.backtestrun')),
            ],
            options={
                'indexes': [models.Index(fields=['run', 'mode'], name='backtests_m_run_id_292bf1_idx')],
            },
        ),
        migrations.CreateModel(
            name='RobustnessRow',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('kind', models.CharField(max_length=32)),
                ('label', models.CharField(max_length=64)),
                ('oos_return', models.FloatField(blank=True, null=True)),
                ('oos_sharpe', models.FloatField(blank=True, null=True)),
                ('oos_dd', models.FloatField(blank=True, null=True)),
                ('trades', models.IntegerField(blank=True, null=True)),
                ('extras', models.JSONField(blank=True, default=dict)),
                ('run', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='robustness_rows', to='backtests.backtestrun')),
            ],
            options={
                'indexes': [models.Index(fields=['run', 'kind'], name='backtests_r_run_id_f23cca_idx')],
            },
        ),
    ]
