# Generated by Django 6.1 on 2026-08-27 13:53

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Dataset',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('symbol', models.CharField(default='XAUUSD', max_length=32)),
                ('timeframe', models.CharField(default='1H', max_length=8)),
                ('source_name', models.CharField(max_length=255)),
                ('raw_path', models.CharField(max_length=1024)),
                ('cache_path', models.CharField(max_length=1024)),
                ('rows_m1', models.IntegerField()),
                ('rows_h1', models.IntegerField()),
                ('start_ts', models.DateTimeField(blank=True, null=True)),
                ('end_ts', models.DateTimeField(blank=True, null=True)),
                ('validation', models.JSONField(default=dict)),
                ('volume_usable', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
